### ISSUE TITLE
Any demo of this?

### ISSUE THREAD

**Issue by BryleHelll** [tliron/vncj#1]

**Comment by tliron** [comment]
[This](https://github.com/tliron/vncj/tree/master/modules/vncj-1.6/src/vncjdemo) looks like a demo.

**Comment by BryleHelll** [comment]
> [This](https://github.com/tliron/vncj/tree/master/modules/vncj-1.6/src/vncjdemo) looks like a demo.

No. I mean a test video or picture

**Comment by tliron** [comment]
There is a photo [here](https://emblemparade.com/projects/vncj/).

**Comment by BryleHelll** [comment]
Ok
